require:
- rubocop-rails

AllCops:
  Exclude:
  - 'Gemfile'
  - 'config/**/*'
  - 'config.ru'
  - 'spec/spec_helper.rb'
  - 'spec/rails_helper.rb'
  - 'bin/**/*'
  - 'node_modules/**/*'

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/CaseIndentation:
  EnforcedStyle: end

Lint/AmbiguousBlockAssociation:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
  - spec/**/*
  - db/migrate/*

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Max: 120
  IgnoredPatterns:
  - "^\\s*describe"
  - "^\\s*context"
  - "^\\s*it"
  Exclude:
  - db/migrate/20191011181410_devise_token_auth_create_users.rb

Metrics/MethodLength:
  Enabled: false
  Exclude:
  - "db/**/*"

Rails:
  Enabled: true

Rails/SaveBang:
  Enabled: true

Rails/TimeZone:
  EnforcedStyle: strict

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

