plugins:
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  TargetRailsVersion: 7.0
  NewCops: enable
  Exclude:
    - "Gemfile"
    - "config/**/*"
    - "config.ru"
    - "spec/spec_helper.rb"
    - "spec/rails_helper.rb"
    - "bin/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "tmp/**/*"
    - "coverage/**/*"
    - "db/schema.rb"

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - "^\\s*describe"
    - "^\\s*context"
    - "^\\s*it"
  Exclude:
    - "db/migrate/*"

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/CaseIndentation:
  EnforcedStyle: end

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/DuplicateBranch:
  Exclude:
    - "db/seeds.rb"

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "db/migrate/*"
    - "db/seeds.rb"
    - "lib/tasks/**/*"

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Exclude:
    - "db/seeds.rb"

Metrics/MethodLength:
  Enabled: false
  Exclude:
    - "db/**/*"

Metrics/PerceivedComplexity:
  Exclude:
    - "db/seeds.rb"

Rails:
  Enabled: true

Rails/SaveBang:
  Enabled: true

Rails/TimeZone:
  EnforcedStyle: strict

Rails/I18nLocaleTexts:
  Enabled: false

Rails/ReversibleMigration:
  Exclude:
    - "db/migrate/*"

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

RSpec/RepeatedExampleGroupDescription:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false
