FROM ruby:3.3.7-alpine

ENV APP_PATH=/app \
    BUNDLE_VERSION=2.6.2 \
    BUNDLE_PATH=/usr/local/bundle/gems \
    RAILS_LOG_TO_STDOUT=true \
    RAILS_PORT=3000

RUN apk add --no-cache \
    build-base=0.5-r3 \
    curl=8.14.1-r2 \
    git=2.47.3-r0 \
    postgresql17-client=17.7-r0 \
    postgresql17-dev=17.7-r0 \
    tzdata=2025c-r0 \
    vips=8.15.3-r5 \
    vips-dev=8.15.3-r5 \
    yaml-dev=0.2.5-r2 \
 && rm -rf /var/cache/apk/*

WORKDIR $APP_PATH

RUN gem install bundler --version "$BUNDLE_VERSION" --no-document

COPY Gemfile Gemfile.lock ./
RUN bundle install --jobs 4 --retry 3

HEALTHCHECK --interval=30s --timeout=3s --start-period=60s --retries=3 \
    CMD curl -f http://localhost:$RAILS_PORT/up || exit 1

COPY --chmod=755 ./entrypoints/development.sh /usr/local/bin/development.sh

EXPOSE $RAILS_PORT

ENTRYPOINT ["development.sh"]
CMD ["puma", "-C", "config/puma.rb"]
