FROM ruby:3.2.1-alpine

#  Docker-specific Environment Variables
ENV APP_PATH /app
ENV BUNDLE_VERSION 2.2.21
ENV BUNDLE_PATH /usr/local/bundle/gems
ENV TMP_PATH /tmp/
ENV RAILS_LOG_TO_STDOUT true
ENV RAILS_PORT 3000

# Install Depencenices
RUN apk -U add --no-cache \
build-base \
tzdata \
postgresql-dev \
postgresql-client \
vips \
&& rm -rf /var/cache/apk/*

RUN mkdir $APP_PATH
WORKDIR $APP_PATH

# Begin
COPY ./entrypoints/development.sh /usr/local/bin/development.sh
RUN chmod +x /usr/local/bin/development.sh
ENTRYPOINT ["development.sh"]
EXPOSE $RAILS_PORT
CMD ["puma", "-C", "config/puma.rb"]
