require:
- rubocop-rails

AllCops:
  Exclude:
  - 'Gemfile'
  - 'config/**/*'
  - 'config.ru'
  - 'spec/spec_helper.rb'
  - 'spec/rails_helper.rb'
  - 'bin/**/*'

Metrics/BlockLength:
  Exclude:
  - spec/**/*
  - db/migrate/*

Metrics/MethodLength:
  Exclude:
  - db/migrate/*

Metrics/LineLength:
  Max: 80
  IgnoredPatterns:
    - "^\\s*describe"
    - "^\\s*context"
    - "^\\s*it"

Metrics/AbcSize:
  Exclude:
  - db/migrate/*

Rails:
  Enabled: true

Rails/SaveBang:
  Enabled: true

Rails/TimeZone:
  EnforcedStyle: strict

Style/Documentation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
