source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '>=2.6.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.0'
# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'
# Use Puma as the app server
gem 'puma', '~> 3.11'

# irb is a gem now instead of being packaged with Ruby
gem 'irb'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.7'

# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false

# this gem is required in all environments to allow using it in the database seeds file
gem 'factory_bot_rails', '~> 5.0.2'

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'

# a gem providing a helpful wrapper for PostgreSQL's full text search
gem 'pg_search', '~> 2.3.0'

# allows soft-deleting database rows
gem 'discard', '~> 1.1.0'

# handles authentication
gem 'devise_token_auth', '~> 1.1.3'

group :development, :test do
  gem 'awesome_print', '~> 1.8.0'
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails', '~> 3.8.0'
  gem 'rubocop-rspec'
  gem 'rubocop-rails'
end

group :development do
  gem 'annotate', '~> 2.7.5'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'

  # Mina is our deployment tool
  gem 'mina', '~> 1.2.3'
  gem 'mina-puma', '~> 1.1.0', require: false
end

group :test do
  gem 'shoulda-matchers', '~> 4.1.2'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
