test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

digitalocean:
  service: S3
  endpoint: <%= Rails.application.credentials.dig(:digitalocean, :endpoint) %>
  access_key_id: <%= Rails.application.credentials.dig(:digitalocean, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:digitalocean, :secret_access_key) %>
  region: <%= Rails.application.credentials.dig(:digitalocean, :region) %>
  bucket: <%= Rails.application.credentials.dig(:digitalocean, :bucket) %>
  public: true

# Local storage for production (used in hybrid mode)
local_production:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Hybrid storage - saves to both local and cloud, reads local first
hybrid:
  service: Mirror
  primary: local_production
  mirrors:
    - digitalocean
