name: Rails

on:
  push:
    branches:
      - 'master'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      - name: Install Gems
        run: |
          bundle install --jobs 4 --retry 3

      - name: Run Lints
        run: |
          bundle exec rubocop
  test:
    name: Tests
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_DB: blackbook_test
          POSTGRES_USER: blackbook
          POSTGRES_PASSWORD: blackbook_test_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      - name: Install Gems
        run: |
          bundle install --jobs 4 --retry 3

      - name: Run Tests
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://blackbook:blackbook_test_pass@localhost:5432/blackbook_test
        run: |
          bundle exec rspec
